spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
